// Every NESA HSC exam paper, linked straight to the official PDF on nsw.gov.au.
// content/papers.json is generated by scripts/build-papers.mjs (links only, never NESA
// content) and checked weekly. Lazy — check-budget fails the build if it reaches the
// critical path. "Done" ticks live in this browser only.
import { useCallback, useMemo, useState } from "react";
import data from "../../content/papers.json";
import ui from "../../content/papers-ui.json";
import site from "../../content/site.json";
import { read, write } from "../lib/storage.ts";
import { useCalc } from "../lib/state.tsx";
import { t } from "../lib/text.ts";
import { Glass, Section } from "./ui.tsx";

type Kind = keyof typeof ui.kinds;
interface File { kind: string; label: string; size: string; path: string }
interface Year { year: number; page: string; files: File[] }
interface Pack { slug: string; name: string; archive: boolean; page: string; courseIds: string[]; successor?: string; years: Year[] }
interface Course { name: string; courseIds: string[]; successor?: string; years: (Year & { old: boolean })[] }

const DONE_KEY = "hsc-papers-done";
const ORIGIN = data.origin;
// One card per course: current and old-syllabus packs merged, newest year first.
const COURSES: Course[] = (() => {
  const by = new Map<string, Course>();
  for (const p of data.courses as Pack[]) {
    // NESA's titles vary in case between current and archive packs ("Dutch continuers").
    const key = p.name.toLowerCase();
    const c = by.get(key) ?? { name: p.name, courseIds: [], years: [] };
    if (!p.archive) c.name = p.name;
    c.courseIds = [...new Set([...c.courseIds, ...p.courseIds])];
    c.successor ??= p.successor;
    c.years.push(...p.years.map((y) => ({ ...y, old: p.archive })));
    by.set(key, c);
  }
  for (const c of by.values()) c.years.sort((a, b) => b.year - a.year || Number(a.old) - Number(b.old));
  return [...by.values()];
})();

/** "English Advanced HSC exam 2023 – Paper 1" → "Paper 1": the part after the dash, if any. */
const suffix = (label: string) => label.split(/\s[–—-]\s/).slice(1).join(" – ");
const loadDone = (): Set<string> => { try { return new Set(JSON.parse(read(DONE_KEY) ?? "[]") as string[]); } catch { return new Set(); } };

const Pdf = () => (
  <svg aria-hidden="true" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="shrink-0">
    <path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z" /><path d="M14 3v5h5" />
  </svg>
);

function YearRow({ c, y, done, toggle }: { c: Course; y: Course["years"][number]; done: Set<string>; toggle: (k: string) => void }) {
  const exams = y.files.filter((f) => f.kind === "exam");
  const key = exams[0]?.path ?? y.page;
  return (
    <li className="paper-year">
      <label className="paper-tick" title={t(ui.markDone, { year: y.year })}>
        <input type="checkbox" checked={done.has(key)} onChange={() => toggle(key)} aria-label={`${t(ui.markDone, { year: y.year })} (${c.name})`} />
      </label>
      <div className="min-w-0 flex-1">
        <p className="flex items-center gap-2 text-[0.92rem] font-semibold num">
          {y.year}{y.old && <span className="pill">{ui.oldSyllabus}</span>}
        </p>
        <div className="mt-1.5 flex flex-wrap gap-1.5">
          {y.files.map((f) => {
            const name = f.kind === "external" ? t(ui.external, { site: f.label }) : ui.kinds[f.kind as Kind] ?? f.label;
            const sub = f.kind === "external" ? "" : suffix(f.label);
            return (
              <a key={f.path} href={f.kind === "external" ? f.path : ORIGIN + f.path} target="_blank" rel="noopener noreferrer" className={`paper-link ${f.kind === "exam" ? "paper-link-primary" : ""}`}>
                <Pdf /><span>{name}{sub && ` · ${sub}`}</span>
                {f.size && <span className="paper-size">{f.size.replace(/^PDF\s*/i, "")}</span>}
                <span className="sr-only">{f.label} {f.kind === "external" ? ui.opensExternal : ui.opensNew}</span>
              </a>
            );
          })}
          <a href={ORIGIN + y.page} target="_blank" rel="noopener noreferrer" className="paper-link paper-link-quiet">
            <span>{ui.feedback}</span><span className="sr-only">{ui.opensPage}</span>
          </a>
        </div>
      </div>
    </li>
  );
}

export default function Papers() {
  const { data: calc } = useCalc();
  const [q, setQ] = useState("");
  const [mineOnly, setMineOnly] = useState(false);
  const [old, setOld] = useState(false);
  const [open, setOpen] = useState<Set<string>>(() => new Set());
  const [done, setDone] = useState(loadDone);
  const mine = useMemo(() => new Set(calc.subjects.map((s) => s.courseId)), [calc.subjects]);
  const isMine = useCallback((c: Course) => c.courseIds.some((id) => mine.has(id)), [mine]);

  const toggle = (k: string) => {
    const next = new Set(done);
    if (next.has(k)) next.delete(k); else next.add(k);
    setDone(next);
    write(DONE_KEY, JSON.stringify([...next]));
  };
  const shown = useMemo(() => {
    const words = q.toLowerCase().split(/\s+/).filter(Boolean);
    return COURSES
      .map((c) => ({ ...c, years: old ? c.years : c.years.filter((y) => !y.old) }))
      .filter((c) => c.years.length && (!mineOnly || isMine(c)) && words.every((w) => `${c.name} ${c.successor ?? ""}`.toLowerCase().includes(w)))
      .sort((a, b) => Number(isMine(b)) - Number(isMine(a)));
  }, [q, mineOnly, old, isMine]);

  return (
    <Section id="papers" kicker={site.kickers.papers} title={ui.title} intro={ui.intro}>
      <Glass className="glass-sm mb-4 flex flex-wrap items-end gap-x-5 gap-y-3 p-4">
        <label className="field min-w-[240px] flex-[2_1_280px]">{ui.search}
          <input className="input" type="search" placeholder={ui.searchPlaceholder} value={q} onChange={(e) => setQ(e.target.value)} />
        </label>
        <label className="flex items-center gap-2 pb-2.5 text-[0.86rem]">
          <input type="checkbox" checked={mineOnly} onChange={(e) => setMineOnly(e.target.checked)} disabled={!mine.size} />{ui.mineOnly}
        </label>
        <label className="flex items-center gap-2 pb-2.5 text-[0.86rem]">
          <input type="checkbox" checked={old} onChange={(e) => setOld(e.target.checked)} />{ui.archive}
        </label>
      </Glass>
      {old && <p className="mb-3 max-w-[80ch] text-[0.8rem] text-foreground-3">{ui.oldNote}</p>}
      <p className="mb-3 text-[0.8rem] text-foreground-3" role="status" aria-live="polite">
        {shown.length ? t(shown.length === 1 ? ui.count1 : ui.count, { n: shown.length }) : t(ui.none, { q })}
      </p>
      <ul className="grid gap-3">
        {shown.map((c) => {
          const exams = c.years.length;
          const nDone = c.years.filter((y) => done.has(y.files.find((f) => f.kind === "exam")?.path ?? y.page)).length;
          const from = c.years.at(-1)!.year, to = c.years[0]!.year;
          const isOpen = open.has(c.name);
          return (
            <li key={c.name}>
              <Glass as="details" className="glass-sm paper-course" open={isOpen}
                onToggle={(e: React.SyntheticEvent<HTMLDetailsElement>) => {
                  const o = e.currentTarget.open;
                  if (o === isOpen) return;
                  const next = new Set(open); if (o) next.add(c.name); else next.delete(c.name); setOpen(next);
                }}>
                <summary className="flex cursor-pointer items-center gap-3 px-4 py-3.5">
                  <span className="min-w-0 flex-1">
                    <span className="flex flex-wrap items-center gap-2">
                      <b className="text-[0.98rem] font-semibold">{c.name}</b>
                      {isMine(c) && <span className="pill !border-accent/50 !text-accent">{ui.mine}</span>}
                    </span>
                    <span className="mt-0.5 block text-[0.76rem] text-foreground-3">
                      {t(from === to ? ui.year1 : ui.years, { from, to })} · {t(exams === 1 ? ui.papers1 : ui.papers, { n: exams })}
                      {nDone > 0 && <> · <span className="text-gain">{t(ui.done, { d: nDone, n: exams })}</span></>}
                      {c.successor && <span className="block">{t(ui.predecessor, { name: c.successor })}</span>}
                    </span>
                  </span>
                  <svg aria-hidden="true" className="chev shrink-0 text-foreground-3" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="m6 9 6 6 6-6" /></svg>
                </summary>
                {isOpen && (
                  <ul className="border-t border-border/10 px-4 pb-3">
                    {c.years.map((y) => <YearRow key={`${y.year}-${y.old}`} c={c} y={y} done={done} toggle={toggle} />)}
                  </ul>
                )}
              </Glass>
            </li>
          );
        })}
      </ul>
      <p className="mt-4 text-[0.78rem] text-foreground-3">{ui.doneNote}</p>
      <p className="mt-1 text-[0.74rem] text-foreground-3">{t(ui.source, { date: data.generated })}</p>
    </Section>
  );
}
